#!/usr/bin/env bash
# Installs Nginx on web-01:
#+    Listens on port 80.
#+    Returns a page that contains the string Hello World! when queried
#++    at the root with a curl GET request.

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
